name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.12.3


environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  freezed_annotation: ^2.0.3
  html: ^0.15.0
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.11
  console: ^4.1.0
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lint: ^1.10.0
  test: ^1.21.1

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/reverse_engineering/clients/embedded_player_client.dart"
